'use strict';

/**
 * Central configuration for the load-testing suite.
 *
 * Everything is env-driven so the SAME scripts run against a local mock
 * (default) or a real staging instance — you only change env vars, never code.
 *
 * Local (default): a mock Thalos server is started automatically by run-all.js.
 * Staging:         set THALOS_TARGET_URL (+ a seeded JWT) and point at staging.
 *
 * NEVER point this at production. See test/load/README.md.
 */

const jwt = require('jsonwebtoken');

const MOCK_PORT = Number(process.env.LOAD_MOCK_PORT) || 4599;

/** Target under test. Defaults to the local mock server. */
const TARGET_URL = (process.env.THALOS_TARGET_URL || `http://127.0.0.1:${MOCK_PORT}`).replace(
  /\/+$/,
  '',
);

/**
 * Safety rail: never let the suite hammer production. If THALOS_TARGET_URL
 * resolves to a hostname that looks like production, refuse to run. Override
 * only with an explicit LOAD_ALLOW_PROD=1 (documented in README) if a host
 * legitimately trips the heuristic.
 *
 * Deny-by-signal: a hostname is rejected if it carries a prod marker and does
 * NOT carry a non-prod marker (staging/dev/test/preview) or a loopback/local
 * address.
 */
function assertNotProduction(rawUrl) {
  if (!process.env.THALOS_TARGET_URL) return; // local mock, always safe
  if (process.env.LOAD_ALLOW_PROD === '1') return; // explicit opt-out
  let host;
  try {
    host = new URL(rawUrl).hostname.toLowerCase();
  } catch {
    throw new Error(`THALOS_TARGET_URL is not a valid URL: ${rawUrl}`);
  }
  const isLocal =
    host === 'localhost' ||
    host === '127.0.0.1' ||
    host === '::1' ||
    host.endsWith('.local');
  const nonProd = /(staging|stage|dev|develop|test|qa|preview|sandbox|local)/.test(host);
  const prodMarker = /(^|\.)prod(uction)?(\.|$)/.test(host);
  if (!isLocal && !nonProd && prodMarker) {
    throw new Error(
      `Refusing to load-test what looks like a PRODUCTION host: "${host}". ` +
        `Point THALOS_TARGET_URL at staging, or set LOAD_ALLOW_PROD=1 to override.`,
    );
  }
}
assertNotProduction(TARGET_URL);

/** API global prefix (Nest uses setGlobalPrefix('v1')). */
const API_PREFIX = process.env.THALOS_API_PREFIX ?? 'v1';

/** Same secret the app/frontend use to sign JWTs (HS256). */
const JWT_SECRET =
  process.env.JWT_SECRET || 'load-test-secret-do-not-use-in-prod-32chars!!';

/** Seeded test identity. On staging these must match a real seeded user. */
const TEST_USER_ID = process.env.LOAD_TEST_USER_ID || 'load-test-user-0001';
/** Stellar TESTNET wallet (G...). Never a mainnet/production wallet. */
const TEST_WALLET =
  process.env.LOAD_TEST_WALLET ||
  'GLOADTESTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

/**
 * JWT used for every request. On staging you can paste a pre-seeded token via
 * LOAD_TEST_JWT (so you never need the raw secret); otherwise we mint one.
 */
const TOKEN =
  process.env.LOAD_TEST_JWT ||
  jwt.sign({ sub: TEST_USER_ID, email: 'load-test@thalos.local' }, JWT_SECRET, {
    algorithm: 'HS256',
    expiresIn: '2h',
  });

/** Scenario knobs (overridable per run). */
const CONNECTIONS = Number(process.env.LOAD_CONNECTIONS) || 100; // concurrent users
const DURATION = Number(process.env.LOAD_DURATION) || 20; // seconds per scenario
const DATASET_SMALL = Number(process.env.LOAD_DATASET_SMALL) || 500;
const DATASET_LARGE = Number(process.env.LOAD_DATASET_LARGE) || 1000;

/** Simulated Supabase latency for the mock (ms). Ignored on real targets. */
const SIM_DB_LATENCY_MS = Number(process.env.LOAD_SIM_DB_LATENCY_MS) || 4;

function apiUrl(path) {
  const clean = path.replace(/^\/+/, '');
  return `${TARGET_URL}/${API_PREFIX}/${clean}`;
}

function authHeaders() {
  return {
    'content-type': 'application/json',
    authorization: `Bearer ${TOKEN}`,
  };
}

/** A valid CreateAgreementDto body (created_by must equal TEST_WALLET). */
function sampleAgreementBody(overrides = {}) {
  return {
    title: 'Load test agreement',
    description: 'Generated by the load-testing suite',
    amount: '100.00',
    asset: 'USDC',
    agreement_type: 'single',
    created_by: TEST_WALLET,
    milestones: [{ description: 'Deliverable', amount: '100.00', status: 'pending' }],
    participants: [{ wallet_address: TEST_WALLET, role: 'client' }],
    ...overrides,
  };
}

const IS_LOCAL_MOCK = !process.env.THALOS_TARGET_URL;

module.exports = {
  MOCK_PORT,
  TARGET_URL,
  API_PREFIX,
  JWT_SECRET,
  TEST_USER_ID,
  TEST_WALLET,
  TOKEN,
  CONNECTIONS,
  DURATION,
  DATASET_SMALL,
  DATASET_LARGE,
  SIM_DB_LATENCY_MS,
  IS_LOCAL_MOCK,
  apiUrl,
  authHeaders,
  sampleAgreementBody,
};
